name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4  # 升级到 v4
    
    - name: 设置 Python
      uses: actions/setup-python@v5  # 升级到 v5
      with:
        python-version: '3.10'
    
    - name: 安装依赖
      run: |
        pip install PyQt5 pyinstaller
    
    - name: 打包
      run: |
        pyinstaller --onefile --windowed --name="视频音量统一工具" adjust_volume_gui.py
    
    - name: 上传产物
      uses: actions/upload-artifact@v4  # 升级到 v4
      with:
        name: 视频音量统一工具
        path: dist/*.exe
